pipeline:

  prepare:
    image: ubuntu
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# ==============================================
# Build
# ----------------------------------------------

  push:
    image: ubuntu
    environment:
      - ENV=dev
    commands:
      - echo "Hello Byam."
    when:
      event: push
