pipeline:

  prepare:
    image: asia.gcr.io/rls-blt-dev/drone-build:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - gcloud docker -- pull asia.gcr.io/rls-blt-dev/drone-build:latest

# ==============================================
# Build
# ----------------------------------------------

  push:
    image: asia.gcr.io/rls-blt-dev/drone-build:latest
    environment:
      - ENV=dev
    commands:
      - echo "Hello Byam."
    when:
      event: push
